name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Container image scan
      uses: Azure/container-scan@v0
      with:
       image-name: nunofgs/find3-unifi

